version: "3.9"

services:
  backend:
    build: .
    container_name: capone-backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - capone-network

  db:
    image: postgres:16
    container_name: capone-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - capone-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  capone-network:
    driver: bridge

volumes:
  db-data:
